### ISSUE TITLE
Provide a pretrained model please.

### ISSUE THREAD

**Issue by Chenwei-Huang** [hurrrr/Deep-Homography-Estimation-Pytorch#1]
Hello! 
Could you send me a pretrained model please? I have trained a model, but result seems not so good. If possible, i want to make a comparison. My e-mail adress is huangcw98@163.com. 
Thank you very much.

**Comment by paeccher** [comment]
Hello,
I'm sending some results that I've obtained at your email address.

**Comment by Chenwei-Huang** [comment]
Yeah, I have received your results which is very useful. Thank you very much.

**Comment by 2014303345** [comment]
> Yeah, I have received your results which is very useful. Thank you very much.

can you send me a pretrained model please? My trained model's CAE is much higher than the paper
thank you very much,my e-mail adress is 2773484694@qq.com

**Comment by Chenwei-Huang** [comment]
@ 2014303345
I have sent my results to your email.
